FORMAT: 1A
HOST: http://inventory.ftr.com

# Inventory api

An API to get information about inventory equipments and locations.

# Group Equipment Resource

Group all the equipment related resources.

## Equipments Collection

### List all equipments [GET /equipments?subId={subId}]

Get the list of equipments for a subscriber.

+ Parameters
    - subId: 370001594062 (string, optional) - Subscriber's id (USI)    

+ Response 200 (application/json)
    + Attributes (array[Equipment])        

### Get equipment details [GET /equipments/{serialNumber}]

Returns details of an equipment.

+ Parameters
    - serialNumber: FD987654342 (string,required) - serial number of an equipment

+ Response 200 (application/json)
    + Attributes (Equipment)

+ Response 404
    + Attributes (Error)

### Create new equipment [POST /equipments]

+ Request (application/json)

    + Attributes
        - locationId: 1423089881201 (required)
        - subscriberId: 370001594062 (required)
        - serialNumber: 30171R000007 (required)
        - model: AM525 (required)
        - userName: 'mjw424' (optional)     

+ Response 201
    
    + Headers

            Location: /equipments/30171R000007


+ Response 409

    + Attributes (Error)


# Data Structures

## Equipment (object)
- serialNumber: 123455      (number, required) - searial number of an equipments
- locationId: headend 1A    (string, required) - location of the equipments
- model: hdhd               (string,required) - model number of the equipment
- subscriberId: 123455      (string,required) - subscriber information 
- status: aaaa              (string,required) - status of the equipment

## Error (object)
- errorMessage: "The sample error message.",
- developerMessage: "The message for developers that can be used for diagnosis.",
- developerErrorCode: "A url to get more information about the error."

